import os, sys, requests
sys.path.insert(0, '.')
with open('.env') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))

from database import get_site
from template_assembler import assemble_final_html
from wp_publisher import _build_json_ld, _xmlrpc_set_yoast_meta

body_html = """<div class="quick-answer">
<p>The best framework to build a social network in 2026 is ShaunSocial for rapid deployment, or Laravel/React+Node.js for custom builds. ShaunSocial lets you launch a fully-featured social network with native mobile apps in days, while custom frameworks take months and cost significantly more.</p>
</div>

<h2>Why Your Framework Choice Determines Your Social Network's Success</h2>
<p>Choosing the wrong framework to build your social network can cost you everything — and we mean that literally. Developers who start building on the wrong stack often discover the problem six to twelve months in, when they've already spent $40,000 to $80,000 on development and still don't have a working product. The framework you choose determines not just how fast you can launch, but how expensive every new feature will be, how easily you can hire developers, and whether your platform can scale as your user base grows. There is a hidden cost to this decision that most entrepreneurs never calculate upfront: the cost of getting it wrong. A rewrite from scratch — switching from an ill-suited framework to a better one after six months of development — is one of the most expensive mistakes in software. You don't just lose the money already spent; you lose the time, the momentum, and often the team itself.</p>
<p>The single most important strategic question you need to answer first is whether you actually need to build from scratch, or whether a ready-made solution gives you everything you need faster and cheaper. For the majority of entrepreneurs, agencies, and businesses entering the social networking space, a ready-made platform like ShaunSocial eliminates months of development, delivers native mobile apps out of the box, and costs a fraction of custom development. The table below makes this cost difference stark — a custom React+Node.js social network can easily cost 60 times more than a ready-made solution while taking 18 times longer to launch. Understanding this cost structure before you commit to a path is the most important thing this guide will help you do.</p>

<table>
<thead>
<tr><th>Approach</th><th>Cost</th><th>Time to Launch</th><th>Ongoing Maintenance</th></tr>
</thead>
<tbody>
<tr><td>ShaunSocial (Ready-Made)</td><td>$2,499 one-time</td><td>1-3 days</td><td>Low (updates included)</td></tr>
<tr><td>Custom Laravel</td><td>$30,000-80,000</td><td>6-12 months</td><td>High (in-house dev needed)</td></tr>
<tr><td>Custom React+Node.js</td><td>$50,000-150,000</td><td>9-18 months</td><td>High</td></tr>
<tr><td>Open Source (HumHub)</td><td>Free + $5,000 dev</td><td>2-4 weeks</td><td>Medium</td></tr>
</tbody>
</table>

<h2>Social Network Frameworks Comparison Table</h2>
<table>
<thead>
<tr><th>Framework/Platform</th><th>Language</th><th>Best For</th><th>Learning Curve</th><th>Time to Launch</th><th>Mobile App</th><th>Cost</th></tr>
</thead>
<tbody>
<tr><td>ShaunSocial</td><td>PHP/Ready-Made</td><td>All-round launch</td><td>None needed</td><td>1-3 days</td><td>Native iOS+Android</td><td>$2,499</td></tr>
<tr><td>Laravel</td><td>PHP</td><td>Custom builds</td><td>Medium</td><td>6-12 months</td><td>Custom needed</td><td>$30k+</td></tr>
<tr><td>React+Node.js</td><td>JS/JS</td><td>Real-time features</td><td>High</td><td>9-18 months</td><td>React Native</td><td>$50k+</td></tr>
<tr><td>Django</td><td>Python</td><td>Rapid prototyping</td><td>Medium</td><td>4-8 months</td><td>Custom needed</td><td>$25k+</td></tr>
<tr><td>Ruby on Rails</td><td>Ruby</td><td>MVPs</td><td>Medium</td><td>3-6 months</td><td>Custom needed</td><td>$20k+</td></tr>
<tr><td>Vue.js+Express</td><td>JS/JS</td><td>Smaller communities</td><td>Medium</td><td>4-8 months</td><td>Custom needed</td><td>$25k+</td></tr>
</tbody>
</table>

<h2>ShaunSocial: The Fastest Way to Build a Social Network in 2026</h2>
<p>ShaunSocial is the most complete ready-made social network platform available in 2026, and for most entrepreneurs and businesses, it is the clear answer to the question of how to build a social network quickly and affordably. Unlike traditional frameworks that require you to build every feature from scratch, ShaunSocial ships with a fully-featured social networking suite built in and ready to configure: news feed, user profiles, groups, pages, events, marketplace, live streaming, real-time messaging, push notifications, a comprehensive admin panel, multi-language support, and — critically — native iOS and Android mobile apps that are ready to publish to the App Store and Google Play. No coding is required to launch. You install it on your VPS, configure it through the admin panel, add your branding, and you are live within days.</p>
<p>What makes ShaunSocial particularly compelling for developers is that it ships with the full PHP source code. This means you are not locked into a black-box SaaS product — if you want to customize features, add proprietary functionality, or integrate with third-party services, the entire codebase is available to you. This is the best of both worlds: the speed of a ready-made platform with the flexibility of custom development when you need it. The platform is available for a one-time purchase price that covers all features, including future updates. There are no monthly licensing fees eating into your revenue. For entrepreneurs, this pricing model means you can calculate your true cost of ownership on day one rather than watching recurring SaaS fees compound indefinitely.</p>
<p>ShaunSocial is the ideal choice for: entrepreneurs who want to validate a social networking concept without committing to a six-figure custom build; businesses launching branded community platforms for their customers; digital agencies building white-label social networks for clients; and established platforms looking to launch new vertical communities quickly. If you want to see the platform in action before committing, the live demo is available at <a href="https://shaunsocial.com/demo/" target="_blank" rel="noopener">https://shaunsocial.com/demo/</a> and showcases all the features you would receive.</p>
<p><strong>Pros:</strong> fastest launch (days, not months), native mobile app included at no extra cost, full source code ownership, one-time purchase price, active development and updates, all social-network-specific features pre-built and integrated.<br>
<strong>Cons:</strong> requires VPS hosting setup (straightforward but not zero-configuration), PHP knowledge is helpful if you want deeper customizations beyond the admin panel settings.</p>
<p>For a broader comparison of platforms in this category, see our guide to the <a href="https://shaunsocial.com/best-social-network-softwares-in-2025-comparison/" target="_blank" rel="noopener">best social network software</a> available today.</p>

<h2>Laravel: Best PHP Framework for Custom Social Network Development</h2>
<p>Laravel is the most popular PHP MVC framework in the world, and it remains the top choice for development teams that need a custom-built social network with full control over every feature and architecture decision. Laravel's elegant syntax reduces boilerplate and makes complex application logic readable, which matters enormously when you are building something as feature-dense as a social network. The framework's Eloquent ORM is particularly well-suited for the complex relationship modeling that social networks demand: friendships, follows, likes, comments, shares, notifications, activity feeds — all of these involve multi-table relationships and aggregation queries that Eloquent handles cleanly and efficiently. Building a social graph on top of Eloquent is genuinely manageable compared to writing raw SQL or using a less mature ORM.</p>
<p>For real-time social features — live notifications, instant messaging, activity feed updates — Laravel Echo combined with Pusher or a self-hosted WebSocket server (Laravel Reverb, introduced in Laravel 11) provides a robust solution that integrates naturally with the rest of the framework. Laravel's built-in queue system handles the asynchronous processing that high-traffic social networks need: sending thousands of push notifications, processing media uploads, generating thumbnails, computing feed rankings. The framework's authentication system (Sanctum for SPA and mobile APIs, Passport for full OAuth2 server functionality) covers the authentication requirements of any modern social platform. The package ecosystem is extensive — Spatie's permission and media library packages, Intervention Image for media processing, and dozens of other community packages reduce the amount of code you need to write from scratch.</p>
<p>However, Laravel's strengths come with an unavoidable reality: there is no social-network starter kit. Every feature — user profiles, activity feeds, notification systems, messaging, groups, events — needs to be designed and built. A feature-complete social network on Laravel will typically require a team of two to four PHP developers working for six to twelve months, with a realistic budget of $30,000 to $80,000 or more depending on feature scope and developer rates. This is a serious investment that is only justified when you have specific requirements that no ready-made platform can meet. If you are considering Laravel for your social network, also review <a href="https://shaunsocial.com/best-wowonder-alternative-2026/" target="_blank" rel="noopener">WoWonder alternatives</a> — some ready-made PHP social platforms share Laravel's underlying technology but ship with everything pre-built.</p>
<p><strong>Pros:</strong> elegant, readable code architecture; massive package ecosystem; powerful Eloquent ORM; long-term support (LTS) releases; excellent official documentation; strong community support.<br>
<strong>Cons:</strong> no social-network-specific starter kit; slow time to market compared to ready-made platforms; expensive custom development cost; requires ongoing in-house or contracted PHP development.</p>

<h2>React + Node.js: Best for Real-Time Social Network Features</h2>
<p>The combination of React on the frontend and Node.js on the backend represents the technology stack that large-scale social platforms favor for its real-time capabilities and developer experience. React's virtual DOM diffing algorithm handles the kind of frequent, partial UI updates that social networks require constantly: new posts appearing in a feed, notification badges incrementing, message threads updating as new messages arrive, like counts changing in real time. React's component model makes it straightforward to build reusable UI elements — post cards, comment threads, user avatars, notification dropdowns — that maintain consistent behavior across a large codebase. When paired with a state management solution like Redux or Zustand, React scales well as your application's complexity grows.</p>
<p>Node.js on the backend shines for real-time social features specifically because of its event-driven, non-blocking I/O model. Socket.io, the most popular WebSocket library for Node.js, makes implementing live features — real-time notifications, instant messaging, live activity feeds, online presence indicators — significantly more straightforward than it would be in a traditional synchronous server environment. GraphQL pairs exceptionally well with this stack for flexible data fetching, allowing frontend components to request exactly the data they need without over-fetching — which matters at scale when your users are loading complex feed pages with multiple data sources. For teams comfortable with JavaScript throughout the entire stack, the productivity benefits of a single language from database queries to React components are real.</p>
<p>The significant downsides of this stack for social network development are time and cost. A full-featured social network built on React+Node.js requires both frontend and backend specialists — or full-stack JavaScript developers who command premium rates. The tooling ecosystem, while excellent, also has a higher complexity ceiling than PHP stacks: webpack configuration, TypeScript integration, containerization, CI/CD pipelines, and database management all require experienced engineers. Realistically, this stack takes nine to eighteen months to produce a feature-complete social network, with budgets ranging from $50,000 to $150,000 or more. React Native for mobile apps adds further time and cost. This stack is best suited for tech startups with investor funding and experienced JavaScript engineering teams, not for entrepreneurs looking to validate a concept quickly. For a lighter-weight alternative to custom builds, see our overview of <a href="https://shaunsocial.com/best-white-label-social-media-platform-2026/" target="_blank" rel="noopener">white label social media platforms</a>.</p>
<p><strong>Pros:</strong> excellent real-time performance via WebSockets and event-driven architecture; modern, enjoyable developer experience; React Native enables code sharing for mobile apps; GraphQL integration for efficient data fetching.<br>
<strong>Cons:</strong> longest development timeline of any framework option; highest overall cost; requires full-stack JavaScript specialists; significant infrastructure complexity.</p>

<h2>Django: Python Framework for Rapid Social Network Prototyping</h2>
<p>Django's "batteries included" philosophy means the framework ships with nearly everything you need to start building immediately: a built-in ORM, authentication system, form handling, admin interface, templating engine, and URL routing. This comprehensive standard library reduces boilerplate dramatically compared to frameworks that require you to assemble these components from third-party packages. For social network prototyping, this matters a great deal — you can have a working user registration system, profile pages, and basic content model running in days rather than weeks, which is why Django is a popular choice for hackathons and rapid prototyping projects.</p>
<p>Django REST Framework (DRF) is the standard approach for building the API layer that modern social network frontends consume. DRF provides serializers, viewsets, and authentication classes that make building RESTful APIs systematic and efficient. The built-in Django admin panel is one of the best content moderation and management interfaces in the framework ecosystem — for social networks that need moderators to review user content, manage reported posts, and handle account disputes, the Django admin provides a functional interface with minimal custom development. Python's ecosystem also brings a meaningful advantage that other stacks lack: access to machine learning libraries (scikit-learn, PyTorch, TensorFlow) for building recommendation engines, content moderation classifiers, and spam detection — features that matter as your social network matures and scales.</p>
<p>Django's challenges for social network development are mainly about ecosystem and scaling. Python developers tend to command higher rates than PHP developers in many markets, which affects your development budget. Django's default synchronous request handling (though async support has improved significantly in recent versions) can require more infrastructure configuration to handle the real-time features social networks need. The time to launch a feature-complete social network on Django is typically four to eight months, with costs around $25,000 to $60,000. For teams with Python expertise and plans to integrate ML-driven features, Django is a strong choice. For teams without an existing Python skill set, the hiring and onboarding costs make it harder to justify over Laravel or a ready-made platform. For more context on platforms in this space, see our guide to <a href="https://shaunsocial.com/social-cms-what-it-is-features-and-top-platforms-in-2026/" target="_blank" rel="noopener">social CMS</a> platforms.</p>
<p><strong>Pros:</strong> fast initial prototyping due to batteries-included philosophy; excellent built-in admin panel for moderation; strong ORM for relationship modeling; Python ecosystem for ML and AI integrations.<br>
<strong>Cons:</strong> Python developers often more expensive than PHP alternatives; different hosting requirements from PHP stacks; real-time features require additional configuration; moderate time to market.</p>

<h2>Ruby on Rails: Rapid MVP Development for Social Networks</h2>
<p>Ruby on Rails pioneered the convention-over-configuration approach that many modern frameworks now emulate, and it remains a powerful tool for building working prototypes quickly. The Rails ecosystem has mature solutions for nearly every social network requirement: Devise for user authentication and account management, Pundit or CanCanCan for authorization, ActiveStorage for file uploads and media management, ActionCable for real-time WebSocket features, and ActiveJob for background processing. These components fit together cleanly because Rails' strong conventions mean the ecosystem is built around the same architectural patterns. A Rails developer who knows these gems can assemble a working social network MVP faster than most other frameworks allow.</p>
<p>The Rails advantage for social network MVPs is most visible in the early stages of development, where the framework's scaffolding, generators, and conventions eliminate large amounts of repetitive code. For a startup that needs to validate whether a social networking concept attracts users before investing in a more scalable architecture, Rails can reach a functional prototype in eight to twelve weeks with a small team. DeviseTokenAuth extends the Devise authentication system to support token-based API authentication for mobile apps. The trade-off is that Rails has experienced a meaningful decline in popularity relative to its peak in the early 2010s, which translates to a smaller talent pool and fewer actively maintained gems compared to frameworks like Laravel or React ecosystems.</p>
<p>At high scale, Rails applications sometimes require architectural changes — moving from a monolith to service-oriented components, caching aggressively, or re-implementing performance-critical paths in faster languages. This is not unique to Rails, but the framework's conventions do make certain scaling patterns more awkward than others. For an MVP that needs to prove product-market fit before major investment, Rails is excellent. For a platform expected to grow to hundreds of thousands of users from launch, consider whether you want to build on a stack with a shrinking developer pool or whether a ready-made solution with proven scalability is a better starting point.</p>
<p><strong>Pros:</strong> fastest framework-based MVP development; strong convention-over-configuration reduces boilerplate; ActionCable for real-time features; mature authentication and authorization gems.<br>
<strong>Cons:</strong> declining popularity and shrinking talent pool; may require architectural rewrites at significant scale; smaller gem ecosystem than JavaScript or PHP alternatives.</p>

<h2>Vue.js + Express: Lightweight Stack for Smaller Social Communities</h2>
<p>Vue.js paired with Express.js (running on Node.js) represents a pragmatic middle ground in the JavaScript ecosystem — offering the modern component-based UI architecture of React with a significantly gentler learning curve. Vue's progressive adoption model is one of its key strengths: you can start with simple component integration and incrementally adopt more advanced patterns (Composition API, Pinia state management, Nuxt.js for server-side rendering) as your application's complexity grows. For development teams that are new to JavaScript frameworks or are transitioning from a server-rendered background, Vue presents a less steep initial learning curve than React's JSX and ecosystem complexity.</p>
<p>Express.js on the backend provides a minimal but flexible HTTP framework for Node.js. Unlike Django or Laravel, Express ships with very little built-in functionality — you assemble your stack from middleware: authentication (Passport.js), database ORM (Sequelize or Prisma), validation (Joi or Zod), and WebSocket support (Socket.io). For social network features, Pinia handles reactive state management for features like real-time notification counts and live message updates. This flexibility is a strength for teams that want precise control over their dependencies, but a potential risk for teams that lack experience choosing and integrating the right packages. The Vue+Express stack is well-suited and cost-effective for smaller social networks targeting defined niches — community platforms serving under 10,000 users, interest-based communities, or B2B professional networks with bounded scope. Build time for a feature-complete but modest social network is typically four to eight months with a budget around $25,000 to $40,000.</p>
<p><strong>Pros:</strong> gentle learning curve compared to React ecosystem; good choice for smaller-scale community platforms; consistent JavaScript language throughout the stack; flexible middleware-based architecture; progressive adoption model.<br>
<strong>Cons:</strong> smaller ecosystem than React for UI components; not ideal for high-scale social platforms; all social networking components require custom implementation; requires careful package selection to avoid dependency issues.</p>

<h2>How to Start Social Network Website Development in 2026: Step-by-Step</h2>

<ol>
<li><strong>Define your niche and target audience.</strong> Before writing a single line of code or purchasing any platform, be specific about who your social network serves and what makes it worth using instead of Facebook, Reddit, or any other established platform. A social network for independent coffee roasters is not competing with Facebook — it serves a specific community with specific needs that Facebook's general-purpose design cannot meet well. Your niche determines your feature priorities, your content moderation approach, and critically, your monetization model. The clearer your niche, the easier it is to recruit early members who are genuinely invested in the community's success. Write a one-paragraph description of your target user and what they will do on your platform every day before you make any technology decisions.</li>

<li><strong>Choose your approach: ready-made or custom build.</strong> With a clear niche defined, the technology decision becomes much more straightforward. For the vast majority of social networking projects — somewhere around 90% — a ready-made platform like ShaunSocial is the correct starting point. ShaunSocial launches in one to three days for a one-time cost of $2,499 and includes native iOS and Android apps. Custom development with Laravel or React+Node.js takes six to eighteen months and costs $30,000 to $150,000. The only cases where custom development is clearly justified from day one are: highly specialized feature requirements that no ready-made platform supports, existing engineering teams with specific technology mandates, or projects where the social network itself is a core proprietary product that investors or acquirers will evaluate on technical architecture.</li>

<li><strong>Set up hosting.</strong> ShaunSocial works on any standard VPS — DigitalOcean Droplets, Linode/Akamai, AWS Lightsail, or any provider running Ubuntu or CentOS with PHP 8.1 or later, MySQL 5.7 or later, and a minimum of 2GB RAM (4GB recommended for active communities). DigitalOcean's $24/month 4GB RAM Droplet is a common starting point and can handle thousands of active users with proper caching in place. For custom framework builds, containerize your application with Docker from the beginning — this makes local development consistent, staging environments reproducible, and production deployment dramatically simpler. Establish your CI/CD pipeline (GitHub Actions, GitLab CI, or similar) early rather than bolting it on after months of manual deployments.</li>

<li><strong>Configure your core features.</strong> For ShaunSocial, the admin panel handles the majority of configuration — enabling or disabling features, setting up categories, configuring email notifications, customizing the theme, and managing user permissions — all within hours of installation. Custom builds require weeks or months to implement these same features from scratch: user authentication and session management, profile creation and editing, the activity feed with efficient pagination and caching, the notification system, media upload and storage handling, messaging infrastructure, and admin moderation tools. Each of these is a significant engineering effort in isolation; building all of them simultaneously requires careful project management and a well-coordinated team.</li>

<li><strong>Launch, market, and iterate quickly.</strong> A social network's success is determined far more by community quality than by technical sophistication, and the biggest risk for any new platform is launching to an empty experience. Before opening registration to the public, seed the platform with content — post in every group, create sample events, populate the feed with interesting discussions, and demonstrate what an active community looks like. Invite a cohort of trusted early users — friends, existing customers, beta testers with genuine interest in your niche — and create a feedback loop. Listen to what features they actually use versus what they ignore. The platforms that survive their first year are the ones that iterate quickly on user feedback, not the ones that spent the most on their initial technical build.</li>
</ol>"""

faq_html = """<div class="faq-item"><h3>What is the best framework to build a social network in 2026?</h3><p>ShaunSocial is the best solution for launching a social network in 2026 — it's not a traditional framework but a ready-made platform that includes all social networking features pre-built. For custom framework-based development, Laravel (PHP) is the top choice for its elegant ORM and ecosystem, while React+Node.js excels for real-time features. Most businesses should choose ShaunSocial to launch in days rather than months.</p></div>
<div class="faq-item"><h3>How much does it cost to build a social network website?</h3><p>Costs vary enormously: a ready-made solution like ShaunSocial costs $2,499 as a one-time license and can launch in days. Custom development with Laravel typically costs $30,000-80,000 over 6-12 months. React+Node.js custom builds run $50,000-150,000 over 9-18 months. Open-source options like HumHub are free but require $3,000-10,000 in setup and customization. For most entrepreneurs, a ready-made platform offers the best return on investment.</p></div>
<div class="faq-item"><h3>How long does it take to build a social network?</h3><p>With a ready-made solution like ShaunSocial, you can set up and launch a social network in 1-3 days. With an open-source framework like HumHub, expect 2-4 weeks. Custom builds take significantly longer: Laravel-based social networks typically take 6-12 months, React+Node.js stacks take 9-18 months, and complex enterprise social platforms can take 2-3 years to reach production-quality.</p></div>
<div class="faq-item"><h3>Is Laravel good for building social networks?</h3><p>Laravel is an excellent PHP framework for custom social network development. Its Eloquent ORM handles complex relationship modeling (friendships, follows, likes, notifications) elegantly. Laravel Echo with Pusher enables real-time features. The authentication, queue, and event systems make building social features manageable. However, it still requires months of development and a significant budget. For faster launches, consider ShaunSocial which is built on similar PHP technology but ships all social features pre-built.</p></div>
<div class="faq-item"><h3>Can I build a social network without coding?</h3><p>Yes, with ShaunSocial you can launch a social network without writing a single line of code. The platform ships with a full-featured admin panel for configuration, theming, and content management. You need a VPS server (easily set up on DigitalOcean or similar) but the installation is straightforward. The native iOS and Android apps are also pre-built — just add your branding and submit to the app stores.</p></div>
<div class="faq-item"><h3>How to build a social network website from scratch?</h3><p>Building from scratch involves: (1) Choose a framework — Laravel for PHP developers, React+Node.js for JavaScript teams; (2) Implement user authentication and profiles; (3) Build the activity feed with efficient database queries; (4) Add real-time notifications via WebSockets; (5) Implement media uploads and storage; (6) Build messaging; (7) Create admin/moderation tools; (8) Build mobile apps. This process takes 6-18 months. Most projects save time and money by starting with ShaunSocial instead.</p></div>"""

site = get_site(4)
wp_url = site['wp_url'].rstrip('/')
auth = (site['wp_username'], site['wp_app_password'])
final_html = assemble_final_html(site=site,
    title="Best Frameworks to Build a Social Network in 2026 (Developer Guide)",
    tldr="ShaunSocial is the fastest way to build a social network in 2026, launching in days with native mobile apps included. For custom builds, Laravel is the top PHP framework and React+Node.js excels for real-time features. This guide compares all major options with costs and timelines.",
    content=body_html, faq=faq_html,
    meta_description="Compare the best frameworks to build a social network in 2026: ShaunSocial, Laravel, React, Django & more. Costs, timelines, and which to choose.",
    meta_title="Best Frameworks to Build a Social Network in 2026",
    cta_link="https://shaunsocial.com/demo/", cta_text="Try ShaunSocial Free Demo")
json_ld = _build_json_ld("Best Frameworks to Build a Social Network in 2026 (Developer Guide)", "Article",
    "Compare the best frameworks to build a social network in 2026: ShaunSocial, Laravel, React, Django & more.", faq_html)
full_content = json_ld + "\n" + final_html

# Count words in body_html
import re
word_count = len(re.findall(r'\b\w+\b', re.sub(r'<[^>]+>', ' ', body_html + faq_html)))
print(f"Approximate word count: {word_count}")

resp = requests.post(f"{wp_url}/wp-json/wp/v2/posts/1802",
    json={"title": "Best Frameworks to Build a Social Network in 2026 (Developer Guide)", "content": full_content, "status": "publish"},
    auth=auth, headers={"Content-Type": "application/json"}, timeout=30)
print(f"Status: {resp.status_code}")
if resp.status_code in (200, 201):
    _xmlrpc_set_yoast_meta(wp_url, site['wp_username'], site['wp_app_password'], 1802, {
        "_yoast_wpseo_metadesc": "Compare the best frameworks to build a social network in 2026: ShaunSocial, Laravel, React, Django & more. Costs, timelines, and which to choose.",
        "_yoast_wpseo_focuskw": "best framework to build social network",
        "_yoast_wpseo_title": "Best Frameworks to Build a Social Network in 2026 %%sep%% %%sitename%%",
    })
    print("Done")
else:
    print(resp.text[:500])
